# docker/Dockerfile.ai
FROM python:3.11-slim

WORKDIR /app

#copy ai-service files
COPY ./ai-service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ai-service /app.py

EXPOSE 8000

# Run FastAPI
CMD uvicorn main:app --host 0.0.0.0 --port 8000

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost:8000/health || exit 1
